### ISSUE TITLE
Updating Home Page Text in Admin Web Panel

### ISSUE THREAD

**Issue by Exius99** [dbm-network/extensions#20]
When I adjust the text for the home page in the admin web panel and hit save.
I get redirected to an error page displaying:

`Error: Cannot find module '../config.json.js.js'`

After having found this error in the dashboard.js file at the bottom of the code, correcting it back to `'../config.json'` fixes the problem. I have attached the full error message below.

![Error Message](https://user-images.githubusercontent.com/60278669/79073798-be289480-7ca5-11ea-918c-16121adf15e7.png)

**Comment by your-a-nerd** [comment]
Looks like my ctrl f --> replace messed that up xD. You can wait for a fix or change `../config.json.js.js` to `../config.json` and that should work.

**Comment by Exius99** [comment]
You're all good, I just saved my edits so it's fixed on my side. Just wanted to point it out so others don't encounter it.
